# TODO: use SARIF and github/codeql-action/upload-sarif when we move to GitHub Advanced Security

name: Supply-chain security

on:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'
  push:
    branches:
      - 'release'
      - 'dev'

permissions: {}

jobs:
  scorecard-analysis:
    if: "!contains(github.repository, 'repository-template')"

    name: Scorecard analysis

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.osv.dev:443
            auth.docker.io:443
            bestpractices.coreinfrastructure.org:443
            github.com:443
            index.docker.io:443

      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: Scorecard output
          path: results.sarif