name: Supply-chain security

on:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'
  push:
    branches:
      - 'release'
      - 'dev'

permissions: {}

jobs:
  scorecard-analysis:
    if: "!contains(github.repository, 'repository-template')"

    name: Scorecard analysis

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@686440d3d68a2677061c95a612a89b328badc752
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: Scorecard output
          path: results.sarif