name: Update release branch from dev in template repository

on:
  push:
    branches:
      - 'dev'

permissions: {}

jobs:
  update-branch:
    if: contains(github.repository, 'repository-template')

    name: Update release branch from dev in template repository

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0

      - name: Update
        run: |
          git checkout release
          git branch -m release dummy
          git branch -m dev release
          git push -f origin release